title: Haley Jones
logo: "images/headshot2024.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="www.linkedin.com/in/haleyjo/">LinkedIn</a> 
  <br>
  <a href="pdf/jones_resume23.pdf">Resume</a>
  <br>
  <a href="https://www.GitHub.com/haleymijones/">GitHub</a>  
  <br>
theme: jekyll-theme-minimal
