title: Haley Jones
logo: "images/headshot2024.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://www.linkedin.com/in/haleyjo/">LinkedIn</a> 
  <br>
  <a href="pdf/">Resume</a>
  <br>
theme: jekyll-theme-minimal
